# Generated by Django 5.0.6 on 2024-07-16 17:20

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', cloudinary.models.CloudinaryField(max_length=255, verbose_name='content')),
                ('rank', models.IntegerField()),
            ],
        ),
    ]
