# Generated by Django 5.0.6 on 2024-07-16 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_galleryitem_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitem',
            name='file_type',
            field=models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video')], default='image', max_length=10),
            preserve_default=False,
        ),
    ]
