# Generated by Django 5.0.6 on 2024-08-01 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_galleryitem_file_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=14)),
                ('message', models.TextField()),
                ('contact_method', models.CharField(choices=[('CALL', 'Call'), ('WHATSAPP', 'WhatsApp'), ('EMAIL', 'Email')], max_length=50)),
            ],
        ),
    ]
