# Generated by Django 5.0.6 on 2024-08-06 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='image',
            field=models.FileField(default='', upload_to='contact_media/'),
            preserve_default=False,
        ),
    ]
